import Head from 'next/head';
import { ReactElement } from 'react';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <div className="bg-indigo-200">
      <Head>
        <title>Yehigo Agritech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-orange-100"></main>
    </div>
  );
};

export default Home;

Home.getLayout = (page: ReactElement) => {
  return (
    <PrimaryLayout>
      {/* <SidebarLayout /> */}
      {page}
    </PrimaryLayout>
  );
};
